# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install poetry
      run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install poetry
    - name: Install dependencies
      run: |
          poetry install
    - name: Test with pytest
      run: |
          pytest -m 'number' learning_swe/tests/test_codebase.py
          pytest -m 'string' learning_swe/tests/test_codebase.py
          pytest -m 'test_parametrize' learning_swe/tests/test_codebase.py
          pytest -m 'test_mock' learning_swe/tests/test_codebase.py
          pytest -m 'test_monkeypatch' learning_swe/tests/test_codebase.py
